apiVersion: apps/v1
kind: Deployment
metadata:
  name: meeting-insights-api
  namespace: meeting-insights
  labels:
    app: meeting-insights-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meeting-insights-api
  template:
    metadata:
      labels:
        app: meeting-insights-api
    spec:
      serviceAccountName: meeting-insights-api
      containers:
      - name: api
        image: meeting-insights-api:latest  # Replace with your ECR image
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: meeting-insights-secrets
              key: OPENAI_API_KEY
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: meeting-insights-secrets
              key: API_KEY
              optional: true
        envFrom:
        - configMapRef:
            name: meeting-insights-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
      volumes:
      - name: uploads
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: meeting-insights-api
  namespace: meeting-insights
  labels:
    app: meeting-insights-api
spec:
  selector:
    app: meeting-insights-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP