#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ROOT_DIR=$(cd "${SCRIPT_DIR}/.." && pwd)
ENV_FILE="${ROOT_DIR}/.env"
COMMAND=${1:-up}
WAIT_TIMEOUT_SECONDS=${WAIT_TIMEOUT_SECONDS:-1200}
MEETING_INSIGHTS_PREBUILT=${MEETING_INSIGHTS_PREBUILT:-false}
MEETING_INSIGHTS_VERSION=${MEETING_INSIGHTS_VERSION:-latest}
MEETING_INSIGHTS_IMAGE_PREFIX=${MEETING_INSIGHTS_IMAGE_PREFIX:-ghcr.io/tonnthe1}

log() {
  printf '[meeting-insights] %s\n' "$*"
}

fail() {
  printf '[meeting-insights] ERROR: %s\n' "$*" >&2
  exit 1
}

compose() {
  (cd "${ROOT_DIR}" && docker compose "$@")
}

require_docker() {
  command -v docker >/dev/null 2>&1 || fail "Docker is required: https://docs.docker.com/get-docker/"
  docker info >/dev/null 2>&1 || fail "Docker is installed but the daemon is not running."
  docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 is required."
}

random_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
  elif command -v python3 >/dev/null 2>&1; then
    python3 - <<'PY'
import secrets
print(secrets.token_hex(24))
PY
  else
    od -An -N24 -tx1 /dev/urandom | tr -d ' \n'
  fi
}

create_env() {
  if [[ -f "${ENV_FILE}" ]]; then
    log "Using existing .env file."
    return
  fi

  local postgres_password minio_password api_key
  postgres_password=$(random_secret)
  minio_password=$(random_secret)
  api_key=$(random_secret)

  umask 077
  cat >"${ENV_FILE}" <<EOF
# Generated by scripts/quickstart.sh. Keep this file private.
POSTGRES_USER=meetinguser
POSTGRES_PASSWORD=${postgres_password}
POSTGRES_DB=meeting_insights
POSTGRES_HOST=db
POSTGRES_PORT=5432

REDIS_HOST=redis
REDIS_PORT=6379
REDIS_DB=0
MAX_QUEUE_SIZE=100
MAX_JOB_ATTEMPTS=3
JOB_TTL_SECONDS=86400

AI_PROVIDER=local
LOCAL_LLM_BASE_URL=
LOCAL_LLM_API_KEY=local
LOCAL_LLM_MODEL=meeting-insights
OPENAI_API_KEY=
OPENAI_MODEL=gpt-4o-mini

API_KEY=${api_key}
CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000

FW_MODEL=${FW_MODEL:-small}
FW_DEVICE=cpu
FW_COMPUTE_TYPE=${FW_COMPUTE_TYPE:-int8}
WHISPER_LANGUAGE=
WHISPER_BEAM_SIZE=5

STORAGE_BACKEND=s3
STORAGE_LOCAL_DIR=/app/uploads
S3_BUCKET=meeting-insights
S3_ENDPOINT_URL=http://minio:9000
AWS_REGION=us-east-1
AWS_ACCESS_KEY_ID=meetingadmin
AWS_SECRET_ACCESS_KEY=${minio_password}
DELETE_AUDIO_AFTER_PROCESSING=true

USE_WORKER_SERVICE=true
ALLOW_SYNC_FALLBACK=false
WORKER_HEALTH_PORT=8001
WORKER_READY_FILE=/tmp/meeting-worker-ready
LOG_LEVEL=INFO
DEBUG=false
BIND_ADDRESS=${BIND_ADDRESS:-127.0.0.1}
EOF
  chmod 600 "${ENV_FILE}" 2>/dev/null || true
  log "Created .env with generated local secrets."
}

set_published_images() {
  export API_IMAGE="${MEETING_INSIGHTS_IMAGE_PREFIX}/meeting-insights-api:${MEETING_INSIGHTS_VERSION}"
  export WORKER_IMAGE="${MEETING_INSIGHTS_IMAGE_PREFIX}/meeting-insights-worker:${MEETING_INSIGHTS_VERSION}"
  export FRONTEND_IMAGE="${MEETING_INSIGHTS_IMAGE_PREFIX}/meeting-insights-frontend:${MEETING_INSIGHTS_VERSION}"
}

clear_published_images() {
  unset API_IMAGE WORKER_IMAGE FRONTEND_IMAGE
}

container_health() {
  local service=$1 container_id
  container_id=$(compose ps -q "${service}")
  [[ -n "${container_id}" ]] || { printf 'missing'; return; }
  docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "${container_id}"
}

wait_for_service() {
  local service=$1 timeout=${2:-${WAIT_TIMEOUT_SECONDS}} start now health
  start=$(date +%s)
  while true; do
    health=$(container_health "${service}")
    case "${health}" in
      healthy|running)
        log "${service} is ${health}."
        return
        ;;
      unhealthy|exited|dead)
        compose logs --tail=120 "${service}" || true
        fail "${service} entered state: ${health}"
        ;;
    esac

    now=$(date +%s)
    if (( now - start >= timeout )); then
      compose ps || true
      compose logs --tail=120 "${service}" || true
      fail "Timed out waiting for ${service}; last state: ${health}"
    fi
    sleep 5
  done
}

show_access() {
  local bind_address
  bind_address=$(grep -E '^BIND_ADDRESS=' "${ENV_FILE}" | tail -1 | cut -d= -f2- || true)
  bind_address=${bind_address:-127.0.0.1}
  if [[ "${bind_address}" == "0.0.0.0" ]]; then
    bind_address=localhost
  fi

  cat <<EOF

Meeting Insights is ready.

  App:           http://${bind_address}:3000
  API docs:      http://${bind_address}:8000/docs
  Worker health: http://${bind_address}:8001/ready
  MinIO console: http://${bind_address}:9001

The first transcription can be slower while the Whisper model finishes warming up.
Useful commands:
  bash scripts/quickstart.sh status
  bash scripts/quickstart.sh logs
  bash scripts/quickstart.sh down
EOF
}

start_stack() {
  if [[ "${MEETING_INSIGHTS_PREBUILT}" == "true" || "${MEETING_INSIGHTS_PREBUILT}" == "1" ]]; then
    set_published_images
    log "Pulling published images (${MEETING_INSIGHTS_VERSION})."
    if compose pull backend-api backend-worker frontend; then
      compose up --detach --no-build --remove-orphans
      return
    fi
    log "Published images were unavailable; falling back to a source build."
    clear_published_images
  fi

  log "Building images from the checked-out source."
  compose up --detach --build --remove-orphans
}

up() {
  require_docker
  create_env
  log "Validating Docker Compose configuration."
  compose config --quiet
  start_stack
  wait_for_service backend-api 300
  wait_for_service frontend 300
  wait_for_service backend-worker "${WAIT_TIMEOUT_SECONDS}"
  show_access
}

status_cmd() {
  require_docker
  create_env
  compose ps
}

logs_cmd() {
  require_docker
  create_env
  compose logs --follow --tail=200
}

down() {
  require_docker
  create_env
  compose down
}

reset() {
  require_docker
  create_env
  if [[ "${CONFIRM_RESET:-}" != "yes" ]]; then
    fail "Reset deletes meetings, database data, Redis data, model cache, and MinIO objects. Re-run with CONFIRM_RESET=yes."
  fi
  compose down --volumes --remove-orphans
  log "All local Meeting Insights containers and volumes were removed."
}

doctor() {
  require_docker
  create_env
  if [[ "${MEETING_INSIGHTS_PREBUILT}" == "true" || "${MEETING_INSIGHTS_PREBUILT}" == "1" ]]; then
    set_published_images
  fi
  compose config --quiet
  log "Docker, Compose, environment configuration, and service topology look valid."
}

case "${COMMAND}" in
  up|start) up ;;
  status) status_cmd ;;
  logs) logs_cmd ;;
  down|stop) down ;;
  reset) reset ;;
  doctor|check) doctor ;;
  *)
    cat >&2 <<'EOF'
Usage: bash scripts/quickstart.sh [up|status|logs|down|reset|doctor]
EOF
    exit 2
    ;;
esac
