param(
    [ValidateSet("up", "start", "status", "logs", "down", "stop", "reset", "doctor", "check")]
    [string]$Command = "up"
)

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RootDir = Split-Path -Parent $ScriptDir
$EnvFile = Join-Path $RootDir ".env"
$WaitTimeoutSeconds = if ($env:WAIT_TIMEOUT_SECONDS) { [int]$env:WAIT_TIMEOUT_SECONDS } else { 1200 }
$UsePrebuilt = $env:MEETING_INSIGHTS_PREBUILT -in @("true", "1")
$Version = if ($env:MEETING_INSIGHTS_VERSION) { $env:MEETING_INSIGHTS_VERSION } else { "latest" }
$ImagePrefix = if ($env:MEETING_INSIGHTS_IMAGE_PREFIX) { $env:MEETING_INSIGHTS_IMAGE_PREFIX } else { "ghcr.io/tonnthe1" }

function Write-Log([string]$Message) {
    Write-Host "[meeting-insights] $Message"
}

function Invoke-Compose {
    param([Parameter(ValueFromRemainingArguments = $true)][string[]]$ComposeArgs)
    Push-Location $RootDir
    try {
        & docker compose @ComposeArgs
        if ($LASTEXITCODE -ne 0) {
            throw "docker compose failed with exit code $LASTEXITCODE"
        }
    }
    finally {
        Pop-Location
    }
}

function Test-Docker {
    if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
        throw "Docker Desktop is required: https://docs.docker.com/desktop/"
    }
    & docker info *> $null
    if ($LASTEXITCODE -ne 0) {
        throw "Docker is installed but Docker Desktop is not running."
    }
    & docker compose version *> $null
    if ($LASTEXITCODE -ne 0) {
        throw "Docker Compose v2 is required."
    }
}

function New-Secret {
    $bytes = New-Object byte[] 24
    $generator = [Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $generator.GetBytes($bytes)
    }
    finally {
        $generator.Dispose()
    }
    return -join ($bytes | ForEach-Object { $_.ToString("x2") })
}

function Ensure-Env {
    if (Test-Path $EnvFile) {
        Write-Log "Using existing .env file."
        return
    }

    $postgresPassword = New-Secret
    $minioPassword = New-Secret
    $apiKey = New-Secret
    $model = if ($env:FW_MODEL) { $env:FW_MODEL } else { "small" }
    $computeType = if ($env:FW_COMPUTE_TYPE) { $env:FW_COMPUTE_TYPE } else { "int8" }
    $bindAddress = if ($env:BIND_ADDRESS) { $env:BIND_ADDRESS } else { "127.0.0.1" }

    $content = @"
# Generated by scripts/quickstart.ps1. Keep this file private.
POSTGRES_USER=meetinguser
POSTGRES_PASSWORD=$postgresPassword
POSTGRES_DB=meeting_insights
POSTGRES_HOST=db
POSTGRES_PORT=5432

REDIS_HOST=redis
REDIS_PORT=6379
REDIS_DB=0
MAX_QUEUE_SIZE=100
MAX_JOB_ATTEMPTS=3
JOB_TTL_SECONDS=86400

AI_PROVIDER=local
LOCAL_LLM_BASE_URL=
LOCAL_LLM_API_KEY=local
LOCAL_LLM_MODEL=meeting-insights
OPENAI_API_KEY=
OPENAI_MODEL=gpt-4o-mini

API_KEY=$apiKey
CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000

FW_MODEL=$model
FW_DEVICE=cpu
FW_COMPUTE_TYPE=$computeType
WHISPER_LANGUAGE=
WHISPER_BEAM_SIZE=5

STORAGE_BACKEND=s3
STORAGE_LOCAL_DIR=/app/uploads
S3_BUCKET=meeting-insights
S3_ENDPOINT_URL=http://minio:9000
AWS_REGION=us-east-1
AWS_ACCESS_KEY_ID=meetingadmin
AWS_SECRET_ACCESS_KEY=$minioPassword
DELETE_AUDIO_AFTER_PROCESSING=true

USE_WORKER_SERVICE=true
ALLOW_SYNC_FALLBACK=false
WORKER_HEALTH_PORT=8001
WORKER_READY_FILE=/tmp/meeting-worker-ready
LOG_LEVEL=INFO
DEBUG=false
BIND_ADDRESS=$bindAddress
"@

    $utf8WithoutBom = [System.Text.UTF8Encoding]::new($false)
    [System.IO.File]::WriteAllText(
        $EnvFile,
        $content + [Environment]::NewLine,
        $utf8WithoutBom
    )

    Write-Log "Created .env with generated local secrets."
}

function Set-PublishedImages {
    $env:API_IMAGE = "$ImagePrefix/meeting-insights-api`:$Version"
    $env:WORKER_IMAGE = "$ImagePrefix/meeting-insights-worker`:$Version"
    $env:FRONTEND_IMAGE = "$ImagePrefix/meeting-insights-frontend`:$Version"
}

function Clear-PublishedImages {
    Remove-Item Env:API_IMAGE -ErrorAction SilentlyContinue
    Remove-Item Env:WORKER_IMAGE -ErrorAction SilentlyContinue
    Remove-Item Env:FRONTEND_IMAGE -ErrorAction SilentlyContinue
}

function Get-ContainerHealth([string]$Service) {
    Push-Location $RootDir
    try {
        $containerId = (& docker compose ps -q $Service).Trim()
    }
    finally {
        Pop-Location
    }
    if (-not $containerId) { return "missing" }
    return (& docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' $containerId).Trim()
}

function Wait-Service([string]$Service, [int]$TimeoutSeconds) {
    $started = Get-Date
    while ($true) {
        $health = Get-ContainerHealth $Service
        if ($health -in @("healthy", "running")) {
            Write-Log "$Service is $health."
            return
        }
        if ($health -in @("unhealthy", "exited", "dead")) {
            Invoke-Compose logs --tail=120 $Service
            throw "$Service entered state: $health"
        }
        if (((Get-Date) - $started).TotalSeconds -ge $TimeoutSeconds) {
            Invoke-Compose ps
            Invoke-Compose logs --tail=120 $Service
            throw "Timed out waiting for $Service; last state: $health"
        }
        Start-Sleep -Seconds 5
    }
}

function Start-Stack {
    if ($UsePrebuilt) {
        Set-PublishedImages
        Write-Log "Pulling published images ($Version)."
        Push-Location $RootDir
        try {
            & docker compose pull backend-api backend-worker frontend
            $pullSucceeded = $LASTEXITCODE -eq 0
        }
        finally {
            Pop-Location
        }
        if ($pullSucceeded) {
            Invoke-Compose up --detach --no-build --remove-orphans
            return
        }
        Write-Log "Published images were unavailable; falling back to a source build."
        Clear-PublishedImages
    }

    Write-Log "Building images from the checked-out source."
    Invoke-Compose up --detach --build --remove-orphans
}

function Show-Access {
    $bindLine = Get-Content $EnvFile | Where-Object { $_ -match '^BIND_ADDRESS=' } | Select-Object -Last 1
    $bindAddress = if ($bindLine) { $bindLine.Split('=', 2)[1] } else { "127.0.0.1" }
    if ($bindAddress -eq "0.0.0.0") { $bindAddress = "localhost" }

    Write-Host ""
    Write-Host "Meeting Insights is ready."
    Write-Host ""
    Write-Host "  App:           http://$bindAddress`:3000"
    Write-Host "  API docs:      http://$bindAddress`:8000/docs"
    Write-Host "  Worker health: http://$bindAddress`:8001/ready"
    Write-Host "  MinIO console: http://$bindAddress`:9001"
    Write-Host ""
    Write-Host "The first transcription can be slower while the Whisper model warms up."
}

if ($env:MEETING_INSIGHTS_ENV_ONLY -in @("true", "1")) {
    Ensure-Env
    Write-Log "Environment generation completed without starting Docker."
    return
}

Test-Docker
Ensure-Env

switch ($Command) {
    { $_ -in @("up", "start") } {
        Invoke-Compose config --quiet
        Start-Stack
        Wait-Service "backend-api" 300
        Wait-Service "frontend" 300
        Wait-Service "backend-worker" $WaitTimeoutSeconds
        Show-Access
    }
    "status" { Invoke-Compose ps }
    "logs" { Invoke-Compose logs --follow --tail=200 }
    { $_ -in @("down", "stop") } { Invoke-Compose down }
    "reset" {
        if ($env:CONFIRM_RESET -ne "yes") {
            throw "Reset deletes all local data. Set CONFIRM_RESET=yes and run again."
        }
        Invoke-Compose down --volumes --remove-orphans
        Write-Log "All local containers and volumes were removed."
    }
    { $_ -in @("doctor", "check") } {
        if ($UsePrebuilt) { Set-PublishedImages }
        Invoke-Compose config --quiet
        Write-Log "Docker, Compose, environment configuration, and service topology look valid."
    }
}
