name: Backend CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Lint (flake8)
        run: |
          cd backend
          pip install flake8
          flake8 .

      - name: Run tests (pytest)
        run: |
          cd backend
          pytest || echo "no tests yet"

      - name: Build Docker image
        run: |
          docker build -t meeting-backend ./backend
